name: book_finder_app
description: App to find any book.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^1.4.3
  http: ^0.13.5
  animate_do: ^3.0.2
  transparent_image: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  url_launcher: ^6.1.7
  flutter_localization: ^0.1.10
  simple_shadow: ^0.3.1
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Gentium Book Basic
      fonts:
        - asset: assets/fonts/GentiumBookBasic-Bold.ttf
        - asset: assets/fonts/GentiumBookBasic-Regular.ttf
          style: normal